name: Monthly Issue Report

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly
  workflow_dispatch:     # Allows manual trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO: bh-zhussain/Demo  # Replace with your actual repo name

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run report script
        run: python monthly_report.py

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-issues-report
          path: monthly_issues_report.csv

